In [77]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Muzamil Hussain\\Downloads\\titanic (1).csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [79]:
df.drop(['PassengerId','Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'] , axis=1 ,inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [81]:
target=df.Survived
inputs=df.drop(['Survived'],axis=1)

In [83]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [85]:
inputs = pd.concat([inputs,dummies],axis=1)
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [87]:
inputs.drop('Sex', axis='columns', inplace=True, errors='ignore')

inputs.head(3)

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False

In [89]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [91]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [93]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(7)

   Pclass        Age     Fare  female   male
0       3  22.000000   7.2500   False   True
1       1  38.000000  71.2833    True  False
2       3  26.000000   7.9250    True  False
3       1  35.000000  53.1000    True  False
4       3  35.000000   8.0500   False   True
5       3  29.699118   8.4583   False   True
6       1  54.000000  51.8625   False   True

In [173]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(inputs, target, test_size=0.2)

In [131]:
len(x_train)

712

In [133]:
len(x_test)

179

In [163]:
#now we are going to create the "NAIVE BAYES MODEL"
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [165]:
model.fit(x_train, y_train)

GaussianNB()

In [175]:
model.score(x_test, y_test)

0.770949720670391

In [141]:
#checking the x_test samples
x_test[:10]

     Pclass        Age      Fare  female   male
301       3  29.699118   23.2500   False   True
763       1  36.000000  120.0000    True  False
39        3  14.000000   11.2417    True  False
221       2  27.000000   13.0000   False   True
383       1  35.000000   52.0000    True  False
375       1  29.699118   82.1708    True  False
310       1  24.000000   83.1583    True  False
264       3  29.699118    7.7500    True  False
794       3  25.000000    7.8958   False   True
874       2  28.000000   24.0000    True  False

In [143]:
#Also check the y_test sample
y_test[:10]

301    1
763    1
39     1
221    0
383    1
375    1
310    1
264    0
794    0
874    1
Name: Survived, dtype: int64

In [177]:
#now lets predict 
model.predict(x_test[:10])

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [181]:
#you also can predict the probability that which class has survived
model.predict_proba(x_test[:10])

array([[5.64459214e-02, 9.43554079e-01],
       [6.33438657e-02, 9.36656134e-01],
       [1.58439316e-03, 9.98415607e-01],
       [2.69953306e-02, 9.73004669e-01],
       [6.10953089e-02, 9.38904691e-01],
       [1.38287257e-04, 9.99861713e-01],
       [9.89928389e-01, 1.00716108e-02],
       [9.26142026e-01, 7.38579741e-02],
       [2.14464535e-02, 9.78553546e-01],
       [9.87623616e-01, 1.23763841e-02]])